name: Deploy react app to gh pages

on:
  push:
    branches:
      -main

permisios:
  contents: read
  pages: write
  id-token: write

concurrency:
  groups: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: config/node/frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup: Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cashe: nmp
          cache-dependency-path: config/node/frontend/package-lock.json
      
      - name Install dependencies
        run: npm cl

      - name: Build
        run: npm run build

      - name: Upload artifacts
        users: actions/upload-artifact@v3
        with:
          path: config/node/frontend/build

  deploy:
    enviroment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to gh pages
        id: deployment
        users: actions/deploy-page@v4
