name: build and push and deploy
on:
  push:
    branches:
      - env-test
permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    name: Build & push
    runs-on:
      - self-hosted
  steps:
    - user: actions/checkout@v3
    - name: Print
      run: echo 'witaj'